In [2]:
!pip install geopy

Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.1-py3-none-any.whl.metadata (1.6 kB)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
Downloading geographiclib-2.1-py3-none-any.whl (40 kB)
Installing collected packages: geographiclib, geopy

   ---------------------------------------- 0/2 [geographiclib]
   ---------------------------------------- 0/2 [geographiclib]
   ---------------------------------------- 0/2 [geographiclib]
   -------------------- ------------------- 1/2 [geopy]
   -------------------- ------------------- 1/2 [geopy]
   -------------------- ------------------- 1/2 [geopy]
   -------------------- ------------------- 1/2 [geopy]
   -------------------- ------------------- 1/2 [geopy]
   -------------------- ------------------- 1/2 [geopy]
   -------------------- ------------------- 1/2 [geopy]
   -------------------- ------------------- 1/2 [geopy]
   -------------------- ------------------- 1/2 [geopy]
   ---------------------------------------- 2/2 [geopy]

Successfully installed geographiclib-2.1 geopy-2.4.1

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\amras\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\amras\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\amras\anaconda3\Lib\site-packages)

In [1]:
import pandas as pd
import re
from pathlib import Path
from rapidfuzz import fuzz, process
from geopy.geocoders import Nominatim
from geopy.distance import geodesic
from collections import defaultdict
import time
from tqdm import tqdm
import math

In [7]:
# Load data
DATA_DIR = Path("data")
RAW_DIR = DATA_DIR / "raw"
OUTPUT_DIR = Path("output")
GTFS_DIR = RAW_DIR / "ttc_gtfs"

unique_df = pd.read_csv(OUTPUT_DIR / "unique_locations_with_ids.csv")
ml_df = pd.read_csv(OUTPUT_DIR / "ml_dataset_ready.csv")
stops_df = pd.read_csv(GTFS_DIR / "stops.txt")
routes_df = pd.read_csv(GTFS_DIR / "routes.txt")
trips_df = pd.read_csv(GTFS_DIR / "trips.txt")
stop_times_df = pd.read_csv(GTFS_DIR / "stop_times.txt")

# normalization function
COMMON_FIXES = {
    "TRITION": "TRITON",
    "BOROUGHQ": "BOROUGH",
    "BOROUG": "BOROUGH",
    "BOUROUGH": "BOROUGH",
    "KNIFGHTSB": "KNIGHTSBRIDGE",
    "KNIGHTSBR": "KNIGHTSBRIDGE",
    "EDLIOU": "EDILOU",
    "HRONER": "HORNER",
    "MCNICOL": "MCNICOLL",
    "NAIRIN": "NAIRN",
    "ABOT": "ABBOT",
    "ABBEY": "ABBEY",
}

def normalize_location_combined(text):
    if not isinstance(text, str):
        return ""
    text = text.upper().strip()
    for old, new in COMMON_FIXES.items():
        text = text.replace(old, new)

    text = re.sub(r"\bAND\b", "&", text)
    text = re.sub(r"\bAT\b", "&", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def canonical_intersection(text):
    text = normalize_location_combined(text)
    if "&" not in text:
        return None
    parts = text.split("&")
    if len(parts) != 2:
        return None
    streets = []

    for p in parts:
        p = re.sub(
            r"\b(ST|STREET|RD|ROAD|AVE|AV|AVENUE|DR|DRIVE|BLVD|HWY)\b",
            "", p
        )
        p = p.strip()
        if p:
            streets.append(p)

    if len(streets) == 2:
        return "|".join(sorted(streets))
    return None
    
# Drop stops with missing coordinates
stops_df = stops_df.dropna(subset=['stop_lat', 'stop_lon'])
print(f"Loaded {len(stops_df)} GTFS stops with valid coordinates")
print(f"Loaded {len(unique_df)} unique locations")
print(f"Loaded {len(ml_df)} ML rows")

# Extract routes per location from ML dataset (only the 50 routes)
routes_per_location = ml_df.groupby('location_id')['route'].apply(
    lambda x: list(set(x.dropna().astype(str)))).to_dict()

unique_df['routes_list'] = unique_df['location_id'].map(routes_per_location)
unique_df['routes_list'] = unique_df['routes_list'].apply(lambda x: x if isinstance(x, list) else [])

valid_route_ids = set(ml_df['route'].dropna().astype(str).unique())
print(f"Number of routes in bus data: {len(valid_route_ids)}")

# Normalise GTFS stop names and build exact lookup
print("Normalising GTFS stops")
tqdm.pandas(desc="Normalising GTFS")
stops_df['normalized'] = stops_df['stop_name'].progress_apply(normalize_location_combined)

gtfs_lookup = {}  # normalized_key -> (stop_name, lat, lon)
for _, row in stops_df.iterrows():
    key = row['normalized']
    if key and key not in gtfs_lookup:
        gtfs_lookup[key] = (row['stop_name'], row['stop_lat'], row['stop_lon'])

canonical_gtfs_lookup = defaultdict(list)
for _, row in stops_df.iterrows():
    c = canonical_intersection(row["normalized"])
    if c:
        canonical_gtfs_lookup[c].append(
            (
                row["stop_name"],
                row["stop_lat"],
                row["stop_lon"]
            )
        )
        
gtfs_keys = list(gtfs_lookup.keys())
print(f"Unique GTFS normalized keys: {len(gtfs_keys)}")

# Blocking dictionary
blocked = defaultdict(list)
for key in gtfs_keys:
    block = key[:2] if len(key) >= 2 else key
    blocked[block].append(key)

# Build route->stops mapping for ONLY the routes present in bus data
trip_route = dict(zip(trips_df['trip_id'], trips_df['route_id']))

stop_info = {}
for _, row in stops_df.iterrows():
    stop_info[row['stop_id']] = (row['stop_name'], row['normalized'])

route_stops = defaultdict(set)
for _, row in stop_times_df.iterrows():
    trip_id = row['trip_id']
    stop_id = row['stop_id']
    route_id = trip_route.get(trip_id)
    if route_id and str(route_id) in valid_route_ids and stop_id in stop_info:
        _, norm_stop = stop_info[stop_id]
        route_stops[str(route_id)].add(norm_stop)

# Convert route_stops sets to lists for faster iteration
route_stops = {k: list(v) for k, v in route_stops.items()}
print(f"Built route->stops mapping for {len(route_stops)} routes (filtered to {len(valid_route_ids)} bus routes)")

# Helper functions
GEOCODE_FALLBACK = True   

def exact_match(norm_key):
    return gtfs_lookup.get(norm_key, None)
# Cache for route-restricted fuzzy matches
fuzzy_cache = {}

def fuzzy_match(norm_key, route_ids=None, score_cutoff=75):
    cache_key = (norm_key, tuple(sorted(route_ids)) if route_ids else None)
    if cache_key in fuzzy_cache:
        return fuzzy_cache[cache_key]
    
    block = norm_key[:2] if len(norm_key) >= 2 else norm_key
    if route_ids and len(route_ids) > 0:
        candidates = []
        for rid in route_ids:
            candidates.extend(route_stops.get(str(rid), []))
        candidates = list(dict.fromkeys(candidates))
        if not candidates:
            candidates = blocked.get(block, gtfs_keys)
    else:
        candidates = blocked.get(block, gtfs_keys)
    
    if not candidates:
        fuzzy_cache[cache_key] = (None, None, None, None, 0)
        return None, None, None, None, 0
    
    result = process.extractOne(norm_key, candidates, scorer=fuzz.WRatio, score_cutoff=score_cutoff)
    if result:
        best_key, score, _ = result
        stop_name, lat, lon = gtfs_lookup[best_key]
        if lat is not None and lon is not None and math.isfinite(lat) and math.isfinite(lon):
            fuzzy_cache[cache_key] = (stop_name, lat, lon, best_key, score)
            return stop_name, lat, lon, best_key, score
    fuzzy_cache[cache_key] = (None, None, None, None, 0)
    return None, None, None, None, 0

# Cache for full fuzzy
full_fuzzy_cache = {}

def full_fuzzy_match(norm_key, score_cutoff=70):
    cache_key = (norm_key, score_cutoff)
    if cache_key in full_fuzzy_cache:
        return full_fuzzy_cache[cache_key]
    block = norm_key[:2] if len(norm_key) >= 2 else norm_key
    candidates = blocked.get(block, gtfs_keys)
    if not candidates:
        full_fuzzy_cache[cache_key] = (None, None, None, None, 0)
        return None, None, None, None, 0
    result = process.extractOne(norm_key, candidates, scorer=fuzz.WRatio, score_cutoff=score_cutoff)
    if result:
        best_key, score, _ = result
        stop_name, lat, lon = gtfs_lookup[best_key]
        if lat is not None and lon is not None and math.isfinite(lat) and math.isfinite(lon):
            full_fuzzy_cache[cache_key] = (stop_name, lat, lon, best_key, score)
            return stop_name, lat, lon, best_key, score
    full_fuzzy_cache[cache_key] = (None, None, None, None, 0)
    return None, None, None, None, 0

def is_address_like(text):
    return bool(re.search(r'\d', text)) and len(text.split()) >= 2

geolocator = Nominatim(user_agent="ttc_location_updater")
geocode_cache = {}

def geocode_address(address):
    if address in geocode_cache:
        return geocode_cache[address]
    try:
        time.sleep(1)
        loc = geolocator.geocode(f"{address}, Toronto, ON", timeout=10)
        if loc is not None:
            lat, lon = loc.latitude, loc.longitude
            if math.isfinite(lat) and math.isfinite(lon):
                geocode_cache[address] = (lat, lon)
                return lat, lon
    except Exception:
        pass
    geocode_cache[address] = (None, None)
    return None, None

def find_nearest_stop(lat, lon):
    if lat is None or lon is None or not (math.isfinite(lat) and math.isfinite(lon)):
        return None, None, None, None
    min_dist = float('inf')
    best = None
    for _, row in stops_df.iterrows():
        s_lat, s_lon = row['stop_lat'], row['stop_lon']
        if not (math.isfinite(s_lat) and math.isfinite(s_lon)):
            continue
        d = geodesic((lat, lon), (s_lat, s_lon)).meters
        if d < min_dist:
            min_dist = d
            best = row
    if best is not None:
        return best['stop_name'], best['stop_lat'], best['stop_lon'], min_dist
    return None, None, None, None

# Process each unique location
results = []
unmatched_ids = []
geocode_attempts = 0

for idx, row in tqdm(unique_df.iterrows(), total=len(unique_df), desc="Matching locations"):
    loc_id = row['location_id']
    norm_key = row['location']
    raw = row['location']
    routes = row['routes_list']
    best_norm = norm_key
    best_stop_name = None
    best_lat = None
    best_lon = None
    match_type = "unmatched"

    # ---- Tier 1 ----
    match = exact_match(norm_key)
    if match:
        stop_name, lat, lon = match
        best_norm = stop_name
        best_stop_name = stop_name
        best_lat = lat
        best_lon = lon
        match_type = "exact"
        results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
            'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
        continue

    # ---- Tier 1.5 Canonical intersection ----
    canonical = canonical_intersection(norm_key)
    if canonical and canonical in canonical_gtfs_lookup:
    
        stop_name, lat, lon = canonical_gtfs_lookup[canonical][0]
    
        best_norm = stop_name
        best_stop_name = stop_name
        best_lat = lat
        best_lon = lon
        match_type = "intersection_exact"
        results.append({
            'location_id': loc_id,
            'normalized_best': best_norm,
            'gtfs_stop_name': best_stop_name,
            'stop_lat': best_lat,
            'stop_lon': best_lon,
            'match_type': match_type
        })
    
        continue
    

    # ---- Tier 2: Route-restricted fuzzy (cutoff 80, then 75) ----
    stop_name, lat, lon, matched_key, score = fuzzy_match(norm_key, route_ids=routes, score_cutoff=80)
    if not stop_name:
        stop_name, lat, lon, matched_key, score = fuzzy_match(norm_key, route_ids=routes, score_cutoff=75)
    if stop_name:
        best_norm = stop_name
        best_stop_name = stop_name
        best_lat = lat
        best_lon = lon
        match_type = f"fuzzy_{score}"
        results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
            'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
        continue

    # ---- Tier 3: Full fuzzy (no route restriction, cutoffs 70,65,60) ----
    stop_name, lat, lon, matched_key, score = full_fuzzy_match(norm_key, score_cutoff=70)
    # if not stop_name:
    #     stop_name, lat, lon, matched_key, score = full_fuzzy_match(norm_key, score_cutoff=65)
    # if not stop_name:
    #     stop_name, lat, lon, matched_key, score = full_fuzzy_match(norm_key, score_cutoff=60)
    if stop_name:
        best_norm = stop_name
        best_stop_name = stop_name
        best_lat = lat
        best_lon = lon
        match_type = f"fullfuzzy_{score}"
        results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
            'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
        continue

    # ---- Tier 4: Geocoding ----
    if GEOCODE_FALLBACK and (is_address_like(raw) or is_address_like(norm_key)):
        addr = raw if is_address_like(raw) else norm_key
        lat, lon = geocode_address(addr)
        geocode_attempts += 1
        if lat is not None and lon is not None and math.isfinite(lat) and math.isfinite(lon):
            stop_name, s_lat, s_lon, dist = find_nearest_stop(lat, lon)
            if stop_name:
                best_norm = stop_name
                best_stop_name = stop_name
                best_lat = s_lat
                best_lon = s_lon
                match_type = f"geo_{dist:.0f}m"
                results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
                    'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
                continue

    # ---- Tier 5: Unmatched ----
    unmatched_ids.append(loc_id)
    results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
        'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})

print(f"Geocoding attempted for {geocode_attempts} locations (if enabled)")

# Merge and save
update_df = pd.DataFrame(results)
updated_unique = unique_df.merge(update_df, on='location_id', how='left')
updated_unique['location'] = updated_unique['normalized_best']
updated_unique['stop_lat'] = updated_unique['stop_lat']
updated_unique['stop_lon'] = updated_unique['stop_lon']
updated_unique['match_type'] = updated_unique['match_type']
updated_unique.drop(columns=['normalized_best', 'routes_list'], inplace=True, errors='ignore')

updated_unique.to_csv(OUTPUT_DIR / "unique_locations_lookup1.csv", index=False)

print(f"\nUpdated unique locations saved to {OUTPUT_DIR / 'unique_locations_lookup1.csv'}")
print(f"Total locations: {len(updated_unique)}")
print(f"Matched: {len(update_df[update_df['match_type'] != 'unmatched'])}")
print(f"Unmatched: {len(update_df[update_df['match_type'] == 'unmatched'])}")

C:\Users\amras\AppData\Local\Temp\ipykernel_5764\4159422594.py:66: DtypeWarning: Columns (0: trip_id, 1: trip_short_name) have mixed types. Specify dtype option on import or set low_memory=False.
  trips_df = pd.read_csv(GTFS_DIR / "trips.txt")
C:\Users\amras\AppData\Local\Temp\ipykernel_5764\4159422594.py:67: DtypeWarning: Columns (0: trip_id, 1: stop_headsign) have mixed types. Specify dtype option on import or set low_memory=False.
  stop_times_df = pd.read_csv(GTFS_DIR / "stop_times.txt")

Loaded 9838 GTFS stops with valid coordinates
Loaded 20262 unique locations
Loaded 152088 ML rows
Number of routes in bus data: 50
Normalising GTFS stops

Normalising GTFS: 100%|██████████| 9838/9838 [00:00<00:00, 33789.94it/s]

Unique GTFS normalized keys: 8161
Built route->stops mapping for 50 routes (filtered to 50 bus routes)

Matching locations: 100%|██████████| 20262/20262 [04:48<00:00, 70.17it/s]

Geocoding attempted for 100 locations (if enabled)

Updated unique locations saved to output\unique_locations_lookup1.csv
Total locations: 20262
Matched: 17559
Unmatched: 2703

In [8]:
unmatched = updated_unique[updated_unique['match_type']=="unmatched"]
print(len(unmatched))
unmatched[['location_id','location']].head(100)

2703

      location_id                location
28             29     FENSIDE AND ROYWOOD
59             60  BERTRAN AND BIRCHMOUNT
92             93      CONNOR AND SUNRISE
135           136                 KITTERY
207           208               HEDGEWOOD
...           ...                     ...
1970         1971         AND OLD ORCHARD
1977         1978  BELMONT AND ROXBOROUGH
2007         2008  NORTHEY AND WOODSWORTH
2009         2010  BRIA AND PLEASANT VIEW
2023         2024       MALLE AND TALGART

[100 rows x 2 columns]

In [13]:
# SECOND PASS MATCHING ONLY UNMATCHED LOCATIONS
# Street Pair Exact -> Fuzzy WRatio -> Save lookup2
DATA_DIR = Path("data")
RAW_DIR = DATA_DIR / "raw"
OUTPUT_DIR = Path("output")
GTFS_DIR = RAW_DIR / "ttc_gtfs"

unique_df = pd.read_csv(OUTPUT_DIR / "unique_locations_lookup1.csv")
stops_df = pd.read_csv(GTFS_DIR / "stops.txt")

stops_df = stops_df.dropna(subset=["stop_lat", "stop_lon"])
print("Total locations:", len(unique_df))

# Get only unmatched
unmatched_df = unique_df[unique_df["match_type"]=="unmatched"].copy()
print("Unmatched before second pass:", len(unmatched_df))

# Normalization
COMMON_FIXES = {
    "TRITION":"TRITON",
    "BOROUGHQ":"BOROUGH",
    "BOROUG":"BOROUGH",
    "BOUROUGH":"BOROUGH",
    "KNIFGHTSB":"KNIGHTSBRIDGE",
    "KNIGHTSBR":"KNIGHTSBRIDGE",
    "EDLIOU":"EDILOU",
    "HRONER":"HORNER",
    "MCNICOL":"MCNICOLL",
    "NAIRIN":"NAIRN",
    "ABOT":"ABBOT"
}

def normalize_location_combined(text):
    if not isinstance(text,str):
        return ""

    text=text.upper().strip()
    for old,new in COMMON_FIXES.items():
        text=text.replace(old,new)
        
    text=re.sub(r"\bAND\b","&", text)
    text=re.sub(r"\bAT\b","&", text)
    text=re.sub(r"\s+"," ",text)
    return text.strip()

# Street pair extraction
def street_pair(text):
    text=normalize_location_combined(text)
    if "&" not in text:
        return None

    parts=text.split("&")
    if len(parts)!=2:
        return None
        
    streets=[]
    for p in parts:
        p=re.sub(
            r"\b(ST|STREET|RD|ROAD|AVE|AV|AVENUE|DR|DRIVE|BLVD|BOULEVARD|HWY)\b",
            "",
            p
        )
        p=p.strip()
        
        if p:
            streets.append(p)

    if len(streets)==2:

        return "|".join(
            sorted(streets)
        )
    return None

# Normalize GTFS
print("Normalizing GTFS")
tqdm.pandas(desc="GTFS normalization")

stops_df["normalized"] = (stops_df["stop_name"].progress_apply(normalize_location_combined))

# Build GTFS lookup
gtfs_lookup={}
for _,row in stops_df.iterrows():
    key=row["normalized"]
    if key not in gtfs_lookup:
        gtfs_lookup[key]=(
            row["stop_name"],
            row["stop_lat"],
            row["stop_lon"]
        )

gtfs_keys=list(gtfs_lookup.keys())
print("GTFS keys:",len(gtfs_keys))

# Build street pair lookup
print("Building street pair lookup")

street_lookup={}
for _,row in stops_df.iterrows():
    key=street_pair(row["stop_name"])

    if key:
        street_lookup[key]=(
            row["stop_name"],
            row["stop_lat"],
            row["stop_lon"]
        )
        
print("Street pair keys:", len(street_lookup))

# Process unmatched
results=[]
for _,row in tqdm(
    unmatched_df.iterrows(),
    total=len(unmatched_df),
    desc="Second pass matching"
):

    loc_id=row["location_id"]
    original=row["location"]
    result={

        "location_id":loc_id,
        "normalized_best":original,
        "gtfs_stop_name":None,
        "stop_lat":None,
        "stop_lon":None,
        "match_type":"unmatched"

    }

    # Tier 1: Street pair exact
    pair=street_pair(original)
    if pair in street_lookup:
        stop,lat,lon = street_lookup[pair]
        result.update({
            "normalized_best":stop,
            "gtfs_stop_name":stop,
            "stop_lat":lat,
            "stop_lon":lon,
            "match_type":"street_pair_exact"
        })

        results.append(result)
        continue

    # Tier 2: Fuzzy WRatio
    norm=normalize_location_combined(original)
    fuzzy_result=process.extractOne(
        norm,
        gtfs_keys,
        scorer=fuzz.WRatio
    )

    if fuzzy_result:
        best_key,score,_=fuzzy_result
        # threshold
        if score >= 75:
            stop,lat,lon = gtfs_lookup[best_key]
            result.update({
                "normalized_best":stop,
                "gtfs_stop_name":stop,
                "stop_lat":lat,
                "stop_lon":lon,
                "match_type":
                    f"second_fuzzy_{score}"
            })

    results.append(result)

# Create second pass dataframe
second_df=pd.DataFrame(results)
print(
    "\nSecond pass matched:",
    len(
        second_df[
            second_df["match_type"]!="unmatched"
        ]
    )
)

# Merge back
updated = unique_df.merge(
    second_df,
    on="location_id",
    how="left",
    suffixes=("","_new")
)

for col in [
    "normalized_best",
    "gtfs_stop_name",
    "stop_lat",
    "stop_lon",
    "match_type"
]:
    
    new_col=col+"_new"
    if new_col in updated.columns:
        updated[col]=(
            updated[new_col]
            .combine_first(
                updated[col]
            )
        )

        updated.drop(
            columns=[new_col],
            inplace=True
        )

updated["location"]=(
    updated["normalized_best"]
    .combine_first(
        updated["location"]
    )
)

updated.drop(
    columns=[
        "normalized_best"
    ],
    inplace=True,
    errors="ignore"
)

# Save
output_file = (OUTPUT_DIR /"unique_locations_lookup2.csv")
updated.to_csv(output_file, index=False)
print("\nSaved:")
print(output_file)
print("\nFinal results:")
print(updated["match_type"].value_counts())

Total locations: 20262
Unmatched before second pass: 2703
Normalizing GTFS

GTFS normalization: 100%|██████████| 9838/9838 [00:00<00:00, 32665.69it/s]

GTFS keys: 8161
Building street pair lookup
Street pair keys: 6262

Second pass matching: 100%|██████████| 2703/2703 [02:34<00:00, 17.52it/s]

Second pass matched: 2585

Saved:
output\unique_locations_lookup2.csv

Final results:
match_type
fuzzy_85.5                     12128
fuzzy_90.0                      2063
second_fuzzy_85.5               1716
intersection_exact              1467
second_fuzzy_90.0                729
                               ...
fullfuzzy_94.73684210526316        1
fuzzy_95.65217391304348            1
fuzzy_90.68181818181817            1
fullfuzzy_76.36363636363636        1
fuzzy_82.5                         1
Name: count, Length: 289, dtype: int64

In [14]:
unmatched_final = updated[updated["match_type"]=="unmatched"][["location_id", "location"]]
print(len(unmatched_final))
unmatched_final.head(100)

118

       location_id                location
343            344                 UNKNOWN
1935          1936            ENTIRE ROUTE
2142          2143              HUDDLESTON
2241          2242                BLEECKER
2263          2264       FREDERICK TISDALE
...            ...                     ...
16956        16957                 BERKHAM
16985        16986                 QMG6 8P
17264        17265  NEIL MCNEIL HIGHSCHOOL
17450        17451                   SANBA
17639        17640       CNE PRINCES GATES

[100 rows x 2 columns]

In [21]:
file = OUTPUT_DIR / "unique_locations_lookup2.csv"
updated = pd.read_csv(file)

# Remove classification column
if "unmatched_category" in updated.columns:
    updated.drop(
        columns=["unmatched_category"],
        inplace=True
    )

# Ensure unmatched rows have null location fields
mask = updated["match_type"] == "unmatched"
updated.loc[mask, "gtfs_stop_name"] = None
updated.loc[mask, "stop_lat"] = None
updated.loc[mask, "stop_lon"] = None

# Save back
updated.to_csv(file, index=False)
print("Updated:")
print(file)
print("\nRemaining unmatched:")
print(
    updated["match_type"]
    .value_counts()
    .get("unmatched",0)
)

Updated:
output\unique_locations_lookup2.csv

Remaining unmatched:
118

In [22]:
updated = pd.read_csv(OUTPUT_DIR / "unique_locations_lookup2.csv")
# Remove old classification column if it exists
if "unmatched_category" in updated.columns:
    updated.drop(columns=["unmatched_category"], inplace=True)

# Keep unmatched rows as NULL values
updated.loc[
    updated["match_type"] == "unmatched",
    [
        "gtfs_stop_name",
        "stop_lat",
        "stop_lon"
    ]
] = None

# Save final lookup
updated.to_csv(OUTPUT_DIR / "unique_locations_lookup.csv", index=False)

print("Saved:")
print(OUTPUT_DIR / "unique_locations_lookup.csv")
print("\nFinal counts:")
print(updated["match_type"].value_counts())

Saved:
output\unique_locations_final.csv

Final counts:
match_type
fuzzy_85.5                     12128
fuzzy_90.0                      2063
second_fuzzy_85.5               1716
intersection_exact              1467
second_fuzzy_90.0                729
                               ...
fullfuzzy_94.73684210526316        1
fuzzy_95.65217391304348            1
fuzzy_90.68181818181817            1
fullfuzzy_76.36363636363636        1
fuzzy_82.5                         1
Name: count, Length: 289, dtype: int64

In [5]:
# # normalization function
# def normalize_location_combined(text):
#     if not isinstance(text, str):
#         return text
#     return text.upper().strip()

# # Load data
# DATA_DIR = Path("data")
# RAW_DIR = DATA_DIR / "raw"
# OUTPUT_DIR = Path("output")
# GTFS_DIR = RAW_DIR / "ttc_gtfs"

# unique_df = pd.read_csv(OUTPUT_DIR / "unique_locations_with_ids.csv")
# ml_df = pd.read_csv(OUTPUT_DIR / "ml_dataset_ready.csv")

# stops_df = pd.read_csv(GTFS_DIR / "stops.txt")
# routes_df = pd.read_csv(GTFS_DIR / "routes.txt")
# trips_df = pd.read_csv(GTFS_DIR / "trips.txt")
# stop_times_df = pd.read_csv(GTFS_DIR / "stop_times.txt")

# # Drop stops with missing coordinates
# stops_df = stops_df.dropna(subset=['stop_lat', 'stop_lon'])
# print(f"Loaded {len(stops_df)} GTFS stops with valid coordinates")
# print(f"Loaded {len(unique_df)} unique locations")
# print(f"Loaded {len(ml_df)} ML rows")

# # Extract routes per location from ML dataset (only the 50 routes)
# routes_per_location = ml_df.groupby('location_id')['route'].apply(
#     lambda x: list(set(x.dropna().astype(str)))).to_dict()

# unique_df['routes_list'] = unique_df['location_id'].map(routes_per_location)
# unique_df['routes_list'] = unique_df['routes_list'].apply(lambda x: x if isinstance(x, list) else [])

# valid_route_ids = set(ml_df['route'].dropna().astype(str).unique())
# print(f"Number of routes in bus data: {len(valid_route_ids)}")

# # Normalise GTFS stop names and build exact lookup
# print("Normalising GTFS stops")
# tqdm.pandas(desc="Normalising GTFS")
# stops_df['normalized'] = stops_df['stop_name'].progress_apply(normalize_location_combined)

# gtfs_lookup = {}  # normalized_key -> (stop_name, lat, lon)
# for _, row in stops_df.iterrows():
#     key = row['normalized']
#     if key and key not in gtfs_lookup:
#         gtfs_lookup[key] = (row['stop_name'], row['stop_lat'], row['stop_lon'])

# gtfs_keys = list(gtfs_lookup.keys())
# print(f"Unique GTFS normalized keys: {len(gtfs_keys)}")

# # Blocking dictionary
# blocked = defaultdict(list)
# for key in gtfs_keys:
#     block = key[:2] if len(key) >= 2 else key
#     blocked[block].append(key)

# # Build route->stops mapping for ONLY the routes present in bus data
# trip_route = dict(zip(trips_df['trip_id'], trips_df['route_id']))

# stop_info = {}
# for _, row in stops_df.iterrows():
#     stop_info[row['stop_id']] = (row['stop_name'], row['normalized'])

# route_stops = defaultdict(set)
# for _, row in stop_times_df.iterrows():
#     trip_id = row['trip_id']
#     stop_id = row['stop_id']
#     route_id = trip_route.get(trip_id)
#     if route_id and str(route_id) in valid_route_ids and stop_id in stop_info:
#         _, norm_stop = stop_info[stop_id]
#         route_stops[str(route_id)].add(norm_stop)

# # Convert route_stops sets to lists for faster iteration
# route_stops = {k: list(v) for k, v in route_stops.items()}
# print(f"Built route->stops mapping for {len(route_stops)} routes (filtered to {len(valid_route_ids)} bus routes)")

# # Helper functions
# GEOCODE_FALLBACK = True   

# def exact_match(norm_key):
#     return gtfs_lookup.get(norm_key, None)

# # Cache for route-restricted fuzzy matches
# fuzzy_cache = {}

# def fuzzy_match(norm_key, route_ids=None, score_cutoff=75):
#     cache_key = (norm_key, tuple(sorted(route_ids)) if route_ids else None)
#     if cache_key in fuzzy_cache:
#         return fuzzy_cache[cache_key]
    
#     block = norm_key[:2] if len(norm_key) >= 2 else norm_key
#     if route_ids and len(route_ids) > 0:
#         candidates = []
#         for rid in route_ids:
#             candidates.extend(route_stops.get(str(rid), []))
#         candidates = list(dict.fromkeys(candidates))
#         if not candidates:
#             candidates = blocked.get(block, gtfs_keys)
#     else:
#         candidates = blocked.get(block, gtfs_keys)
    
#     if not candidates:
#         fuzzy_cache[cache_key] = (None, None, None, None, 0)
#         return None, None, None, None, 0
    
#     result = process.extractOne(norm_key, candidates, scorer=fuzz.partial_ratio, score_cutoff=score_cutoff)
#     if result:
#         best_key, score, _ = result
#         stop_name, lat, lon = gtfs_lookup[best_key]
#         if lat is not None and lon is not None and math.isfinite(lat) and math.isfinite(lon):
#             fuzzy_cache[cache_key] = (stop_name, lat, lon, best_key, score)
#             return stop_name, lat, lon, best_key, score
#     fuzzy_cache[cache_key] = (None, None, None, None, 0)
#     return None, None, None, None, 0

# # Cache for full fuzzy
# full_fuzzy_cache = {}

# def full_fuzzy_match(norm_key, score_cutoff=70):
#     cache_key = (norm_key, score_cutoff)
#     if cache_key in full_fuzzy_cache:
#         return full_fuzzy_cache[cache_key]
#     block = norm_key[:2] if len(norm_key) >= 2 else norm_key
#     candidates = blocked.get(block, gtfs_keys)
#     if not candidates:
#         full_fuzzy_cache[cache_key] = (None, None, None, None, 0)
#         return None, None, None, None, 0
#     result = process.extractOne(norm_key, candidates, scorer=fuzz.partial_ratio, score_cutoff=score_cutoff)
#     if result:
#         best_key, score, _ = result
#         stop_name, lat, lon = gtfs_lookup[best_key]
#         if lat is not None and lon is not None and math.isfinite(lat) and math.isfinite(lon):
#             full_fuzzy_cache[cache_key] = (stop_name, lat, lon, best_key, score)
#             return stop_name, lat, lon, best_key, score
#     full_fuzzy_cache[cache_key] = (None, None, None, None, 0)
#     return None, None, None, None, 0

# def is_address_like(text):
#     return bool(re.search(r'\d', text)) and len(text.split()) >= 2

# geolocator = Nominatim(user_agent="ttc_location_updater")
# geocode_cache = {}

# def geocode_address(address):
#     if address in geocode_cache:
#         return geocode_cache[address]
#     try:
#         time.sleep(1)
#         loc = geolocator.geocode(f"{address}, Toronto, ON", timeout=10)
#         if loc is not None:
#             lat, lon = loc.latitude, loc.longitude
#             if math.isfinite(lat) and math.isfinite(lon):
#                 geocode_cache[address] = (lat, lon)
#                 return lat, lon
#     except Exception:
#         pass
#     geocode_cache[address] = (None, None)
#     return None, None

# def find_nearest_stop(lat, lon):
#     if lat is None or lon is None or not (math.isfinite(lat) and math.isfinite(lon)):
#         return None, None, None, None
#     min_dist = float('inf')
#     best = None
#     for _, row in stops_df.iterrows():
#         s_lat, s_lon = row['stop_lat'], row['stop_lon']
#         if not (math.isfinite(s_lat) and math.isfinite(s_lon)):
#             continue
#         d = geodesic((lat, lon), (s_lat, s_lon)).meters
#         if d < min_dist:
#             min_dist = d
#             best = row
#     if best is not None:
#         return best['stop_name'], best['stop_lat'], best['stop_lon'], min_dist
#     return None, None, None, None

# # Process each unique location
# results = []
# unmatched_ids = []
# geocode_attempts = 0

# for idx, row in tqdm(unique_df.iterrows(), total=len(unique_df), desc="Matching locations"):
#     loc_id = row['location_id']
#     norm_key = row['location']
#     raw = row['location']
#     routes = row['routes_list']
#     best_norm = norm_key
#     best_stop_name = None
#     best_lat = None
#     best_lon = None
#     match_type = "unmatched"

#     # ---- Tier 1 ----
#     match = exact_match(norm_key)
#     if match:
#         stop_name, lat, lon = match
#         best_norm = stop_name
#         best_stop_name = stop_name
#         best_lat = lat
#         best_lon = lon
#         match_type = "exact"
#         results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
#             'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
#         continue

#     # ---- Tier 2: Route-restricted fuzzy (cutoff 80, then 75) ----
#     stop_name, lat, lon, matched_key, score = fuzzy_match(norm_key, route_ids=routes, score_cutoff=80)
#     if not stop_name:
#         stop_name, lat, lon, matched_key, score = fuzzy_match(norm_key, route_ids=routes, score_cutoff=75)
#     if stop_name:
#         best_norm = stop_name
#         best_stop_name = stop_name
#         best_lat = lat
#         best_lon = lon
#         match_type = f"fuzzy_{score}"
#         results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
#             'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
#         continue

#     # ---- Tier 3: Full fuzzy (no route restriction, cutoffs 70,65,60) ----
#     stop_name, lat, lon, matched_key, score = full_fuzzy_match(norm_key, score_cutoff=70)
#     if not stop_name:
#         stop_name, lat, lon, matched_key, score = full_fuzzy_match(norm_key, score_cutoff=65)
#     if not stop_name:
#         stop_name, lat, lon, matched_key, score = full_fuzzy_match(norm_key, score_cutoff=60)
#     if stop_name:
#         best_norm = stop_name
#         best_stop_name = stop_name
#         best_lat = lat
#         best_lon = lon
#         match_type = f"fullfuzzy_{score}"
#         results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
#             'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
#         continue

#     # ---- Tier 4: Geocoding ----
#     if GEOCODE_FALLBACK and (is_address_like(raw) or is_address_like(norm_key)):
#         addr = raw if is_address_like(raw) else norm_key
#         lat, lon = geocode_address(addr)
#         geocode_attempts += 1
#         if lat is not None and lon is not None and math.isfinite(lat) and math.isfinite(lon):
#             stop_name, s_lat, s_lon, dist = find_nearest_stop(lat, lon)
#             if stop_name:
#                 best_norm = stop_name
#                 best_stop_name = stop_name
#                 best_lat = s_lat
#                 best_lon = s_lon
#                 match_type = f"geo_{dist:.0f}m"
#                 results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
#                     'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
#                 continue

#     # ---- Tier 5: Unmatched ----
#     unmatched_ids.append(loc_id)
#     results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
#         'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})

# print(f"Geocoding attempted for {geocode_attempts} locations (if enabled)")

# # Merge and save
# update_df = pd.DataFrame(results)
# updated_unique = unique_df.merge(update_df, on='location_id', how='left')
# updated_unique['location'] = updated_unique['normalized_best']
# updated_unique['stop_lat'] = updated_unique['stop_lat']
# updated_unique['stop_lon'] = updated_unique['stop_lon']
# updated_unique['match_type'] = updated_unique['match_type']
# updated_unique.drop(columns=['normalized_best', 'routes_list'], inplace=True, errors='ignore')

# updated_unique.to_csv(OUTPUT_DIR / "unique_locations_lookup1.csv", index=False)

# print(f"\nUpdated unique locations saved to {OUTPUT_DIR / 'unique_locations_lookup1.csv'}")
# print(f"Total locations: {len(updated_unique)}")
# print(f"Matched: {len(update_df[update_df['match_type'] != 'unmatched'])}")
# print(f"Unmatched: {len(update_df[update_df['match_type'] == 'unmatched'])}")



#------------------------------------------------------------------------------------------------------------------------


# # Normalization function
# def normalize_location_combined(text):
#     if not isinstance(text, str):
#         return text
#     return text.upper().strip()

# # Load data
# unique_df = pd.read_csv(OUTPUT_DIR / "unique_locations_lookup1.csv")
# # Filter to only unmatched
# unmatched_df = unique_df[unique_df['match_type'] == 'unmatched'].copy()
# print(f"Unmatched locations to process: {len(unmatched_df)}")

# # Drop stops with missing coordinates
# # stops_df = stops_df.dropna(subset=['stop_lat', 'stop_lon'])
# print(f"Loaded {len(stops_df)} GTFS stops with valid coordinates")

# routes_per_location = ml_df.groupby('location_id')['route'].apply(lambda x: list(set(x.dropna().astype(str)))).to_dict()

# # Add routes_list to unmatched_df
# unmatched_df['routes_list'] = unmatched_df['location_id'].map(routes_per_location)
# unmatched_df['routes_list'] = unmatched_df['routes_list'].apply(lambda x: x if isinstance(x, list) else [])

# valid_route_ids = set(ml_df['route'].dropna().astype(str).unique())
# print(f"Number of routes in bus data: {len(valid_route_ids)}")

# # Build GTFS lookups
# print("Normalising GTFS stops")
# tqdm.pandas(desc="Normalising GTFS")
# stops_df['normalized'] = stops_df['stop_name'].progress_apply(normalize_location_combined)

# gtfs_lookup = {}
# for _, row in stops_df.iterrows():
#     key = row['normalized']
#     if key and key not in gtfs_lookup:
#         gtfs_lookup[key] = (row['stop_name'], row['stop_lat'], row['stop_lon'])

# gtfs_keys = list(gtfs_lookup.keys())
# print(f"Unique GTFS normalized keys: {len(gtfs_keys)}")

# blocked = defaultdict(list)
# for key in gtfs_keys:
#     block = key[:2] if len(key) >= 2 else key
#     blocked[block].append(key)

# # Route->stops mapping
# trip_route = dict(zip(trips_df['trip_id'], trips_df['route_id']))

# stop_info = {}
# for _, row in stops_df.iterrows():
#     stop_info[row['stop_id']] = (row['stop_name'], row['normalized'])

# route_stops = defaultdict(set)
# for _, row in stop_times_df.iterrows():
#     trip_id = row['trip_id']
#     stop_id = row['stop_id']
#     route_id = trip_route.get(trip_id)
#     if route_id and str(route_id) in valid_route_ids and stop_id in stop_info:
#         _, norm_stop = stop_info[stop_id]
#         route_stops[str(route_id)].add(norm_stop)

# route_stops = {k: list(v) for k, v in route_stops.items()}
# print(f"Built route->stops mapping for {len(route_stops)} routes")

# # Matching functions
# def exact_match(norm_key):
#     return gtfs_lookup.get(norm_key, None)

# fuzzy_cache = {}
# def fuzzy_match(norm_key, route_ids=None, score_cutoff=75):
#     cache_key = (norm_key, tuple(sorted(route_ids)) if route_ids else None)
#     if cache_key in fuzzy_cache:
#         return fuzzy_cache[cache_key]
#     block = norm_key[:2] if len(norm_key) >= 2 else norm_key
#     if route_ids and len(route_ids) > 0:
#         candidates = []
#         for rid in route_ids:
#             candidates.extend(route_stops.get(str(rid), []))
#         candidates = list(dict.fromkeys(candidates))
#         if not candidates:
#             candidates = blocked.get(block, gtfs_keys)
#     else:
#         candidates = blocked.get(block, gtfs_keys)
#     if not candidates:
#         fuzzy_cache[cache_key] = (None, None, None, None, 0)
#         return None, None, None, None, 0
#     result = process.extractOne(norm_key, candidates, scorer=fuzz.partial_ratio, score_cutoff=score_cutoff)
#     if result:
#         best_key, score, _ = result
#         stop_name, lat, lon = gtfs_lookup[best_key]
#         if lat is not None and lon is not None and math.isfinite(lat) and math.isfinite(lon):
#             fuzzy_cache[cache_key] = (stop_name, lat, lon, best_key, score)
#             return stop_name, lat, lon, best_key, score
#     fuzzy_cache[cache_key] = (None, None, None, None, 0)
#     return None, None, None, None, 0

# full_fuzzy_cache = {}
# def full_fuzzy_match(norm_key, score_cutoff=70):
#     cache_key = (norm_key, score_cutoff)
#     if cache_key in full_fuzzy_cache:
#         return full_fuzzy_cache[cache_key]
#     block = norm_key[:2] if len(norm_key) >= 2 else norm_key
#     candidates = blocked.get(block, gtfs_keys)
#     if not candidates:
#         full_fuzzy_cache[cache_key] = (None, None, None, None, 0)
#         return None, None, None, None, 0
#     result = process.extractOne(norm_key, candidates, scorer=fuzz.partial_ratio, score_cutoff=score_cutoff)
#     if result:
#         best_key, score, _ = result
#         stop_name, lat, lon = gtfs_lookup[best_key]
#         if lat is not None and lon is not None and math.isfinite(lat) and math.isfinite(lon):
#             full_fuzzy_cache[cache_key] = (stop_name, lat, lon, best_key, score)
#             return stop_name, lat, lon, best_key, score
#     full_fuzzy_cache[cache_key] = (None, None, None, None, 0)
#     return None, None, None, None, 0

# # Geocoding for all
# geolocator = Nominatim(user_agent="ttc_location_updater")
# geocode_cache = {}

# def geocode_address(address):
#     if address in geocode_cache:
#         return geocode_cache[address]
#     try:
#         time.sleep(1)  # rate limit
#         loc = geolocator.geocode(f"{address}, Toronto, ON", timeout=10)
#         if loc is not None:
#             lat, lon = loc.latitude, loc.longitude
#             if math.isfinite(lat) and math.isfinite(lon):
#                 geocode_cache[address] = (lat, lon)
#                 return lat, lon
#     except Exception:
#         pass
#     geocode_cache[address] = (None, None)
#     return None, None

# def find_nearest_stop(lat, lon):
#     if lat is None or lon is None or not (math.isfinite(lat) and math.isfinite(lon)):
#         return None, None, None, None
#     min_dist = float('inf')
#     best = None
#     for _, row in stops_df.iterrows():
#         s_lat, s_lon = row['stop_lat'], row['stop_lon']
#         if not (math.isfinite(s_lat) and math.isfinite(s_lon)):
#             continue
#         d = geodesic((lat, lon), (s_lat, s_lon)).meters
#         if d < min_dist:
#             min_dist = d
#             best = row
#     if best is not None:
#         return best['stop_name'], best['stop_lat'], best['stop_lon'], min_dist
#     return None, None, None, None

# # Process unmatched locations
# new_results = []
# still_unmatched = []

# for idx, row in tqdm(unmatched_df.iterrows(), total=len(unmatched_df), desc="Filling unmatched"):
#     loc_id = row['location_id']
#     norm_key = row['location']
#     raw = row['location']
#     routes = row['routes_list']

#     best_norm = norm_key
#     best_stop_name = None
#     best_lat = None
#     best_lon = None
#     match_type = "unmatched"

#     # 1. Exact GTFS
#     match = exact_match(norm_key)
#     if match:
#         stop_name, lat, lon = match
#         best_norm = stop_name
#         best_stop_name = stop_name
#         best_lat = lat
#         best_lon = lon
#         match_type = "exact"
#         new_results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
#             'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
#         continue

#     # Route-restricted fuzzy
#     stop_name, lat, lon, matched_key, score = fuzzy_match(norm_key, route_ids=routes, score_cutoff=80)
#     if not stop_name:
#         stop_name, lat, lon, matched_key, score = fuzzy_match(norm_key, route_ids=routes, score_cutoff=75)
#     if stop_name:
#         best_norm = stop_name
#         best_stop_name = stop_name
#         best_lat = lat
#         best_lon = lon
#         match_type = f"fuzzy_{score}"
#         new_results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
#             'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
#         continue

#     # 3. Full fuzzy (cutoffs 70,65,60,55,50,45)
#     found = False
#     for cutoff in [70, 65, 60, 55, 50, 45]:
#         stop_name, lat, lon, matched_key, score = full_fuzzy_match(norm_key, score_cutoff=cutoff)
#         if stop_name:
#             best_norm = stop_name
#             best_stop_name = stop_name
#             best_lat = lat
#             best_lon = lon
#             match_type = f"fullfuzzy_{score}"
#             new_results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
#                 'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
#             found = True
#             break
#     if found:
#         continue

#     # Geocode all remaining
#     lat, lon = geocode_address(raw)
#     if lat is None or lon is None:
#         lat, lon = geocode_address(norm_key)
#     if lat is not None and lon is not None and math.isfinite(lat) and math.isfinite(lon):
#         stop_name, s_lat, s_lon, dist = find_nearest_stop(lat, lon)
#         if stop_name:
#             best_norm = stop_name
#             best_stop_name = stop_name
#             best_lat = s_lat
#             best_lon = s_lon
#             match_type = f"geo_{dist:.0f}m"
#             new_results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
#                 'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})
#             continue

#     # Still unmatched
#     still_unmatched.append(loc_id)
#     new_results.append({'location_id': loc_id, 'normalized_best': best_norm, 'gtfs_stop_name': best_stop_name,
#         'stop_lat': best_lat, 'stop_lon': best_lon, 'match_type': match_type})

# # Update the original CSV
# update_df = pd.DataFrame(new_results)
# # Merge updates back into unique_df
# unique_updated = unique_df.merge(update_df, on='location_id', suffixes=('', '_new'), how='left')
# # For rows that were updated, replace the old values with new ones
# for col in ['location', 'gtfs_stop_name', 'stop_lat', 'stop_lon', 'match_type']:
#     col_new = f"{col}_new"
#     if col_new in unique_updated.columns:
#         unique_updated[col] = unique_updated[col_new].fillna(unique_updated[col])
#         unique_updated.drop(columns=[col_new], inplace=True)

# # Save the updated file
# unique_updated.to_csv(OUTPUT_DIR / "unique_locations_lookup1.csv", index=False)

# print(f"\nUpdated unique locations saved to {OUTPUT_DIR / 'unique_locations_lookup1.csv'}")
# print(f"Total locations: {len(unique_updated)}")
# print(f"Newly matched: {len(update_df[update_df['match_type'] != 'unmatched'])}")
# print(f"Still unmatched: {len(still_unmatched)}")

Unmatched locations to process: 2734
Loaded 9838 GTFS stops with valid coordinates
Number of routes in bus data: 50
Normalising GTFS stops

Normalising GTFS: 100%|██████████| 9838/9838 [00:00<00:00, 304115.17it/s]

Unique GTFS normalized keys: 8164
Built route->stops mapping for 50 routes

Filling unmatched: 100%|██████████| 2734/2734 [04:37<00:00,  9.87it/s]

Updated unique locations saved to output\unique_locations_lookup1.csv
Total locations: 20262
Newly matched: 2578
Still unmatched: 156